
version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./app/dist:/var/www/html
      - ./volumes/nginx/conf.d/:/etc/nginx/conf.d
      - ./volumes/nginx/logs/nginx:/var/log/nginx
    links:
      - medsoft

  db:
    image: postgres:14
    container_name: db_medsoft
    ports:
      - "5433:5432"
    env_file:
      - .env-prod

  medsoft:
    image: vadim2422/medsoft:latest
    env_file:
      - .env-prod
    container_name: medsoft_app
    environment:
      - TZ=Europe/Moscow
    command: sh -c  "sleep 1 && alembic upgrade head && gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8888:8000
    tty: true
    depends_on:
      - db